Wait for vcluster to become available

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -34,6 +34,21 @@ runs:
             --context ${{ inputs.context }} \
             --namespace ${{ inputs.namespace }} \
             --print > ./kubeconfig.yaml
+          
+          vcluster_port=$(yq '.clusters[] | select(key = 0) | .cluster.server' kubeconfig.yaml | cut -d':' -f 3)
+
+          echo "waiting 60s for vcluster to become available..."
+          start_time=$(date +%s)
+          while ! nc -z localhost "$vcluster_port";
+          do
+              now=$(date +%s)
+              if [ $(( now - start_time )) -gt 60 ]; then
+                  echo "ERROR: VCluster port did not become available within 60 seconds"
+                  exit 1
+              fi
+              sleep 1;
+          done
+          
           echo "KUBECONFIG=${PWD}/kubeconfig.yaml" >> $GITHUB_ENV
           echo "vcluster-context=$(echo -n `yq '.contexts[] | select(key = 0) | .name' kubeconfig.yaml`)" >> $GITHUB_OUTPUT
         post: |
